name: Besmellah name

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # چون فقط index.html داریم، کل پوشه ریشه را منتشر می‌کنیم
          # publish_branch: gh-pages # اگر می‌خواهید به شاخه gh-pages دیپلوی شود، این خط را از کامنت درآورید
